#!/usr/bin/env tsx
/**
 * LuxeRealty first-run setup wizard.
 * Run via: npm run setup
 */

import * as readline from 'readline'
import * as fs from 'fs'
import * as path from 'path'
import { execSync } from 'child_process'
import crypto from 'crypto'
import bcrypt from 'bcryptjs'

const rl = readline.createInterface({ input: process.stdin, output: process.stdout })

function ask(question: string, defaultVal = ''): Promise<string> {
  return new Promise(resolve => {
    const hint = defaultVal ? ` [${defaultVal}]` : ''
    rl.question(`${question}${hint}: `, answer => {
      resolve(answer.trim() || defaultVal)
    })
  })
}



async function main() {
  console.log('\n╔═══════════════════════════════════════╗')
  console.log('║      LuxeRealty Setup Wizard          ║')
  console.log('╚═══════════════════════════════════════╝\n')

  // 1. DB mode
  console.log('Database Mode:')
  console.log('  1) Development (SQLite – easy local testing)')
  console.log('  2) Production  (MySQL / MariaDB)\n')
  const dbChoice = await ask('Select mode', '1')

  let dbProvider: string
  let databaseUrl: string

  if (dbChoice === '2') {
    dbProvider = 'mysql'
    console.log('\nMySQL / MariaDB connection details:')
    const host   = await ask('  Host', 'localhost')
    const port   = await ask('  Port', '3306')
    const dbName = await ask('  Database name', 'realestateweb')
    const user   = await ask('  User', 'root')
    const pass   = await ask('  Password', '')
    databaseUrl  = `mysql://${user}:${pass}@${host}:${port}/${dbName}`
  } else {
    dbProvider  = 'sqlite'
    databaseUrl = 'file:./dev.db'
  }

  // 2. JWT secret
  const jwtSecret = await ask('\nJWT Secret (leave blank to auto-generate)', '')
  const resolvedSecret = jwtSecret || crypto.randomBytes(48).toString('hex')

  // 3. Write .env
  const envPath = path.join(process.cwd(), '.env')
  const envContent = `# Generated by setup wizard
NODE_ENV=${dbChoice === '2' ? 'production' : 'development'}
DB_PROVIDER=${dbProvider}
DATABASE_URL="${databaseUrl}"

JWT_SECRET=${resolvedSecret}
JWT_EXPIRES_IN=7d

OPENAI_API_KEY=
ANTHROPIC_API_KEY=
OPENCLAW_WEBHOOK_SECRET=

IDX_API_BASE_URL=https://api.idx.broker/api/1.7
IDX_API_KEY=

NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_GOOGLE_MAPS_KEY=
`
  fs.writeFileSync(envPath, envContent)
  console.log('\n✓ .env file created')

  // 4. Prisma migrate / push
  console.log('\nInitializing database…')
  try {
    if (dbProvider === 'sqlite') {
      execSync('npx prisma db push --skip-generate', { stdio: 'inherit', env: { ...process.env, DATABASE_URL: databaseUrl, DB_PROVIDER: dbProvider } })
    } else {
      execSync('npx prisma migrate deploy', { stdio: 'inherit', env: { ...process.env, DATABASE_URL: databaseUrl, DB_PROVIDER: dbProvider } })
    }
    execSync('npx prisma generate', { stdio: 'inherit' })
    console.log('✓ Database initialized')
  } catch {
    console.error('✗ Database initialization failed. Check your connection string.')
    process.exit(1)
  }

  // 5. Create admin account
  console.log('\nCreate admin account:')
  const adminName  = await ask('  Name', 'Admin')
  const adminEmail = await ask('  Email', 'admin@example.com')
  const adminPass  = await ask('  Password', 'changeme123')
  const passwordHash = await bcrypt.hash(adminPass, 12)

  // Dynamically import Prisma client after generate
  const { PrismaClient } = await import('@prisma/client')
  const prisma = new PrismaClient({ datasourceUrl: databaseUrl })

  try {
    // Seed default stages (skip if any exist)
    const { DEAL_STAGES_DEFAULT } = await import('../lib/constants')
    const stageCount = await prisma.stage.count()
    if (stageCount === 0) {
      for (const stage of DEAL_STAGES_DEFAULT) {
        await prisma.stage.create({ data: { ...stage } })
      }
    }

    const existing = await prisma.user.findUnique({ where: { email: adminEmail } })
    if (existing) {
      console.log('ℹ Admin user already exists, skipping.')
    } else {
      await prisma.user.create({
        data: { name: adminName, email: adminEmail, passwordHash, role: 'admin' },
      })
      console.log('✓ Admin account created')
    }
  } catch (e: unknown) {
    console.error('✗ Failed to create admin user:', e)
  } finally {
    await prisma.$disconnect()
  }

  console.log('\n╔═══════════════════════════════════════╗')
  console.log('║  Setup complete! Run: npm run dev     ║')
  console.log('╚═══════════════════════════════════════╝\n')
  rl.close()
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
