import { NextResponse } from 'next/server'
import * as fs from 'fs'
import * as path from 'path'
import { execSync } from 'child_process'
import { randomBytes } from 'crypto'

export const dynamic = 'force-dynamic'

const ROOT = process.cwd()
const ENV_PATH = path.join(ROOT, '.env')
const SCHEMA_PATH = path.join(ROOT, 'prisma', 'schema.prisma')

function isAlreadySetup(): boolean {
  if (!fs.existsSync(ENV_PATH)) return false
  const content = fs.readFileSync(ENV_PATH, 'utf8')
  const match = content.match(/^JWT_SECRET=(.+)$/m)
  if (!match) return false
  const secret = match[1].trim().replace(/^["']|["']$/g, '')
  return (
    secret.length >= 32 &&
    secret !== 'change_me_to_a_long_random_string_at_least_32_chars'
  )
}

export async function GET() {
  return NextResponse.json({ configured: isAlreadySetup() })
}

export async function POST(req: Request) {
  if (isAlreadySetup()) {
    return NextResponse.json(
      { error: 'Application is already configured.' },
      { status: 403 }
    )
  }

  let body: Record<string, string | undefined>
  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: 'Invalid request body.' }, { status: 400 })
  }

  const {
    environment,
    dbHost, dbPort, dbName, dbUser, dbPass,
    adminName, adminEmail, adminPassword,
    appUrl,
    smtpHost, smtpPort, smtpUser, smtpPass, smtpFrom,
    twilioSid, twilioToken, twilioFrom,
  } = body

  if (!adminName || !adminEmail || !adminPassword) {
    return NextResponse.json(
      { error: 'Admin name, email, and password are required.' },
      { status: 400 }
    )
  }

  const isProduction = environment === 'production'
  const dbProvider = isProduction ? 'mysql' : 'sqlite'
  const databaseUrl = isProduction
    ? `mysql://${encodeURIComponent(dbUser || 'root')}:${encodeURIComponent(dbPass || '')}@${dbHost || 'localhost'}:${dbPort || '3306'}/${dbName || 'realestateweb'}`
    : 'file:./dev.db'

  const jwtSecret = randomBytes(48).toString('hex')
  const resoTokenSecret = randomBytes(32).toString('hex')
  const resoSyncSecret = randomBytes(32).toString('hex')
  const automationSecret = randomBytes(32).toString('hex')

  // Build .env lines
  const envLines: string[] = [
    '# Generated by LuxeRealty Setup Wizard',
    `NODE_ENV=${isProduction ? 'production' : 'development'}`,
    `DB_PROVIDER=${dbProvider}`,
    `DATABASE_URL="${databaseUrl}"`,
    '',
    `JWT_SECRET=${jwtSecret}`,
    `JWT_EXPIRES_IN=7d`,
    '',
    `OPENAI_API_KEY=`,
    `ANTHROPIC_API_KEY=`,
    `OPENCLAW_WEBHOOK_SECRET=`,
    '',
    `NEXT_PUBLIC_APP_URL=${appUrl || 'http://localhost:3000'}`,
    `NEXT_PUBLIC_GOOGLE_MAPS_KEY=`,
    '',
    `RESO_API_BASE_URL=${isProduction ? '' : 'http://localhost:3000/api/mock-reso'}`,
    `RESO_CLIENT_ID=${isProduction ? '' : 'mock-client'}`,
    `RESO_CLIENT_SECRET=${isProduction ? '' : 'mock-secret'}`,
    `RESO_TOKEN_SECRET=${resoTokenSecret}`,
    `RESO_SYNC_SECRET=${resoSyncSecret}`,
    '',
    `AUTOMATION_PROCESS_SECRET=${automationSecret}`,
    `AUTOMATION_INTERVAL_MS=60000`,
  ]

  if (smtpHost) {
    envLines.push(
      '',
      `SMTP_HOST=${smtpHost}`,
      `SMTP_PORT=${smtpPort || '587'}`,
      `SMTP_USER=${smtpUser || ''}`,
      `SMTP_PASS=${smtpPass || ''}`,
      `SMTP_FROM=${smtpFrom || smtpUser || ''}`,
    )
  }

  if (twilioSid) {
    envLines.push(
      '',
      `TWILIO_ACCOUNT_SID=${twilioSid}`,
      `TWILIO_AUTH_TOKEN=${twilioToken || ''}`,
      `TWILIO_FROM_NUMBER=${twilioFrom || ''}`,
    )
  }

  fs.writeFileSync(ENV_PATH, envLines.join('\n') + '\n')

  // Update schema.prisma provider if switching to MySQL
  if (isProduction) {
    let schema = fs.readFileSync(SCHEMA_PATH, 'utf8')
    schema = schema.replace(
      /provider\s*=\s*"sqlite"/,
      'provider = "mysql"'
    )
    fs.writeFileSync(SCHEMA_PATH, schema)
  }

  // Run Prisma DB init
  const spawnEnv = {
    ...process.env,
    DATABASE_URL: databaseUrl,
    DB_PROVIDER: dbProvider,
  }

  try {
    if (dbProvider === 'sqlite') {
      execSync('npx prisma db push --skip-generate', { cwd: ROOT, env: spawnEnv, stdio: 'pipe', shell: true } as unknown as Parameters<typeof execSync>[1])
    } else {
      execSync('npx prisma migrate deploy', { cwd: ROOT, env: spawnEnv, stdio: 'pipe', shell: true } as unknown as Parameters<typeof execSync>[1])
    }
    execSync('npx prisma generate', { cwd: ROOT, env: spawnEnv, stdio: 'pipe', shell: true } as unknown as Parameters<typeof execSync>[1])
  } catch (err: unknown) {
    const e = err as { stderr?: Buffer; message?: string }
    return NextResponse.json(
      {
        error: 'Database initialization failed. Check your connection details.',
        details: e.stderr?.toString() || e.message,
      },
      { status: 500 }
    )
  }

  // Write a temporary CJS script to create the admin user + seed stages
  const DEAL_STAGES = [
    { name: 'New Lead', order: 1, color: '#6366f1' },
    { name: 'Contacted', order: 2, color: '#8b5cf6' },
    { name: 'Showing', order: 3, color: '#f59e0b' },
    { name: 'Offer Made', order: 4, color: '#ef4444' },
    { name: 'Under Contract', order: 5, color: '#10b981' },
    { name: 'Closed', order: 6, color: '#059669' },
  ]

  const tempScript = path.join(ROOT, '.setup-admin-temp.cjs')
  fs.writeFileSync(
    tempScript,
    `
const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');
const stages = ${JSON.stringify(DEAL_STAGES)};

async function main() {
  const prisma = new PrismaClient({
    datasourceUrl: process.env.DATABASE_URL,
  });
  try {
    const hash = await bcrypt.hash(process.env.ADMIN_PASS, 12);
    const existing = await prisma.user.findUnique({
      where: { email: process.env.ADMIN_EMAIL },
    });
    if (!existing) {
      await prisma.user.create({
        data: {
          name: process.env.ADMIN_NAME,
          email: process.env.ADMIN_EMAIL,
          passwordHash: hash,
          role: 'admin',
        },
      });
    }
    const stageCount = await prisma.stage.count();
    if (stageCount === 0) {
      for (const s of stages) {
        await prisma.stage.create({ data: s });
      }
    }
  } finally {
    await prisma.$disconnect();
  }
}

main().catch(e => { console.error(e); process.exit(1); });
`
  )

  try {
    execSync('node .setup-admin-temp.cjs', {
      cwd: ROOT,
      env: { ...spawnEnv, ADMIN_NAME: adminName, ADMIN_EMAIL: adminEmail, ADMIN_PASS: adminPassword },
      stdio: 'pipe',
      shell: true,
    } as unknown as Parameters<typeof execSync>[1])
  } catch (err: unknown) {
    const e = err as { stderr?: Buffer; message?: string }
    return NextResponse.json(
      {
        error: 'Failed to create admin user.',
        details: e.stderr?.toString() || e.message,
      },
      { status: 500 }
    )
  } finally {
    try { fs.unlinkSync(tempScript) } catch { /* ignore */ }
  }

  return NextResponse.json({
    success: true,
    message: 'Setup complete. Restart the server to apply your configuration.',
  })
}
